name: skinviewer
base: core18 
version: '0.2.1'
summary: App for seeing Minecraft Skins
description: |
  App written in Java for seeing Minecraft Skins

  (Works only with Minecraft premium skins)

  Features;

    Seeing player skin (With second layer)
    Seeing player NameMC profile.
    Giving URL to player skin
    Discord RPC Integration

  Issues;

  If you found a bug write to me about it in issues page on github (https://github.com/AndusDEV/SkinViewer/issues)

  Contributing;

    If you want to help me out with this little program just do something you want and push it into main branch. I'll look at it and accept it if I'll see it as a good idea. (https://github.com/AndusDEV/SkinViewer)


grade: stable
confinement: strict
